### PR TITLE
fix subgraph bugs

### LINKED ISSUE #932: latest subgraph doesn't show any orders
https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-flare/0.5/gn

### PR DESCRIPTION
**Pull request by rouzwelt**
## Motivation
resolves #932 

## Solution
fixes the bugs, but the complementary tests needs to be brought over from #937 to cover the new entities well

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [ ] unit-tested any new functionality
- [x] linked any relevant issues or PRs

### CODE REVIEW

File: subgraph/src/clear.ts [hunk 1]
```diff
@@ -14,128 +13,64 @@ import {
...
+    crypto.keccak256(event.address.concat(event.transaction.hash))
   );
-  return Bytes.fromByteArray(orderHash);
 }
 
-export function clearTemporaryDataEntityId(event: ethereum.Event): Bytes {
-  return Bytes.fromByteArray(
-    crypto.keccak256(event.transaction.hash.concat(event.address))
-  );
+export function getOrderHash(value: ethereum.Value): Bytes {
```
Comment (hardyjosh) [inline subgraph/src/clear.ts:22]: this fn arg isn't typed. not all ethereum.Values will result in an order hash

File: subgraph/src/clear.ts [hunk 2]
```diff
@@ -14,128 +13,64 @@ import {
   store,
 } from "@graphprotocol/graph-ts";
 
-export function orderHashFromClearEvent(
-  event: ClearV2,
-  isAlice: boolean
-): Bytes {
-  let orderHash = crypto.keccak256(
-    ethereum.encode(event.parameters[isAlice ? 1 : 2].value.toTuple()[0])!
+export function makeClearV2Id(event: ethereum.Event): Bytes {
```
Comment (hardyjosh) [inline subgraph/src/clear.ts:16]: not typed - will all ethereum.Events give you a clearv2id?

**Review by hardyjosh — CHANGES_REQUESTED** [review]
